### ISSUE TITLE
No examples folder

### ISSUE THREAD

**Issue by sujaymansingh** [larksuite/rsmpeg#113]
The `README` mentions checking out the tests and examples folder (https://github.com/larksuite/rsmpeg/blob/589cd36f6a59a4eda0990e0621b6592bffe911f0/README.md?plain=1#L111), but there is no examples folder.

Perhaps somewhere there is an examples folder that someone forgot to commit?

**Comment by ldm0** [comment]
Thanks for pointing that out. 

There was an `examples` folder containing a shadertoy example which depends on `glfw`. `glfw` is a binding crate and it's hard to compile on Windows without customized configuration, which may introduce confusion to newcomers. Therefore it's deleted: https://github.com/larksuite/rsmpeg/commit/baec7ffd05fbe4f6ad3bffe5998ae13d3f50f0b2.

The tests folder contains most of the examples though, you can take a look.
