### ISSUE TITLE
最新版 0.14.1编译没问题，但是当我运行时报错，win11

### ISSUE THREAD

**Issue by dfsfdfse** [larksuite/rsmpeg#118]
error[E0587]: type has conflicting packed and align representation hints
    --> D:\workbench\rust\ffmpeg-test\target\debug\build\rusty_ffmpeg-74b7e75f9a2f9582\out/binding.rs:2013:1
     |
2013 | pub union __mingw_ldbl_type_t {
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by ldm0** [comment]
Related issue: https://github.com/pgcentralfoundation/pgrx/issues/1132

It seems that `bindgen` doesn't generate bindings for MinGW types correctly. Are you using mingw toolchain? Please link some environment information in issue description(build args etc). It would be helpful if I can reproduce it on my own machine.

**Comment by dfsfdfse** [comment]
ok,It is indeed a MinGW problem,so i remove it
