### ISSUE TITLE
Compilation through vcpkg

### ISSUE THREAD

**Issue by aegroto** [larksuite/rsmpeg#119]
Would you consider the addition of a compilation guide which uses https://github.com/mcgoo/cargo-vcpkg? I have successfully built some personal projects that use rsmpeg by compiling FFMpeg with vcpkg, both on Windows and Linux. The process itself has revealed to be much simpler as after everything is set up you just need to run "cargo vcpkg build" instead of cloning the ffmpeg source by hand, although it may be more difficult to choose a specific ffmpeg version.

Forgot to tell that I am more than willing to help by adding the guide and testing it myself on the current examples.

**Comment by ldm0** [comment]
Building FFmpeg with vcpkg from source code is definitely a road blocker for newcomers, hence it's not mentioned in README. Having a complation guide leveraging `cargo-vcpkg` is great, especially for Windows developers !

If you are willing to add the guide, you can add an additional section in README with section name like `Getting started(with vcpkg)` or something like that. :-D
