### ISSUE TITLE
Running Example Error

### ISSUE THREAD

**Issue by xxscloud5722** [larksuite/rsmpeg#122]
Code：
git： rsmpeg-vcpkg-demo

C:\Users\AA\Desktop\rsmpeg-vcpkg-demo-master>echo %FFMPEG_PKG_CONFIG_PATH%
D:\vcpkg\installed\x64-windows-static-md\lib\pkgconfig

C:\Users\AA\Desktop\rsmpeg-vcpkg-demo-master>cargo vcpkg --verbose build
vcpkg root is D:\vcpkg
    Fetching vcpkg

Message：：

error: linking with `link.exe` failed: exit code: 1120
  |
  = note: "C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\link.exe" "/NOLOGO" "C:\\Users\\AA\\AppData\\Local\\Temp\\rustcUDebEn\\symbols.o" "C:\\Users\\AA\\Desktop\\rsmpeg-vcpkg-demo-master\\target\\debug\\deps\\rsmpeg_vcpkg_demo.14x009273zxltdzv.rcgu.o" "C:\\Users\\AA\\Desktop\\rsmpeg-vcpkg-demo-master\\target\\debug\\deps\\rsmpeg_vcpkg_demo.19ii64hvjq260mbw.rcgu.o" "C:\\Users\\AA\\Desktop\\rsmpeg-vcpkg-demo-master\\target\\debug\\deps\\rsmpeg_vcpkg_demo.265vt5w16atk6yqt.rcgu.o" "C:\\Users\\AA\\Desktop\\rsmpeg-vcpkg-demo-master\\target\\debug\\deps\\rsmpeg_vcpkg_demo.3hmyt0n3tadbqiqn.rcgu.o" "C:\\Users\\AA\\Desktop\\rsmpeg-vcpkg-demo-master\\target\\debug\\deps\\rsmpeg_vcpkg_demo.45z8zrhtcgwwtyrv.rcgu.o" "C:\\Users\\AA\\Desktop\\rsmpeg-vcpkg-demo-master\\target\\debug\\deps\\rsmpeg_vcpkg_demo.4amt6abzq6la6yx6.rcgu.o" "C:\\Users\\AA\\Desktop\\rsmpeg-vcpkg-demo-master\\target\\debug\\deps\\rsmpeg_vcpkg_demo.4n4c25295805ecq2.rcgu.o" "C:\\Users\\AA\\Desktop\\rsmpeg-vcpkg-demo-master\\target\\debug\\deps\\rsmpeg_vcpkg_demo.4petkjx744kw5ie5.rcgu.o" "C:\\Users\\AA\\Desktop\\rsmpeg-vcpkg-demo-master\\target\\debug\\deps\\rsmpeg_vcpkg_demo.5gpvfka59ser635i.rcgu.o" "C:\\Users\\AA\\Desktop\\rsmpeg-vcpkg-demo-master\\target\\debug\\deps\\rsmpeg_vcpkg_demo.pgoc93qhmn1nszl.rcgu.o" "C:\\Users\\AA\\Desktop\\rsmpeg-vcpkg-demo-master\\target\\debug\\deps\\rsmpeg_vcpkg_demo.ypkxbmvjwho5n88.rcgu.o" "C:\\Users\\AA\\Desktop\\rsmpeg-vcpkg-demo-master\\target\\debug\\deps\\rsmpeg_vcpkg_demo.3l5ane5fnmp7mtza.rcgu.o" "/LIBPATH:C:\\Users\\AA\\Desktop\\rsmpeg-vcpkg-demo-master\\target\\debug\\deps" "/LIBPATH:D:\\vcpkg\\installed\\x64-windows-static-md\\lib" "/LIBPATH:C:\\Users\\AA\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "C:\\Users\\AA\\Desktop\\rsmpeg-vcpkg-demo-master\\target\\debug\\deps\\librsmpeg-a432ad4d72d4fcbc.rlib" "C:\\Users\\AA\\Desktop\\rsmpeg-vcpkg-demo-master\\target\\debug\\deps\\libthiserror-203060b4736bfe63.rlib" "C:\\Users\\AA\\Desktop\\rsmpeg-vcpkg-demo-master\\target\\debug\\deps\\librusty_ffmpeg-e40ef72c28dc502c.rlib" "C:\\Users\\AA\\Desktop\\rsmpeg-vcpkg-demo-master\\target\\debug\\deps\\liblibc-d8595f7c09b145ad.rlib" "C:\\Users\\AA\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libstd-0f357f0f8e8eb48f.rlib" "C:\\Users\\AA\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libpanic_unwind-57325150de1d69ac.rlib" "C:\\Users\\AA\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\librustc_demangle-7a221d01d4c27fb2.rlib" "C:\\Users\\AA\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libstd_detect-7bffc6b402bc9229.rlib" "C:\\Users\\AA\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libhashbrown-3fd39796b57f4908.rlib" "C:\\Users\\AA\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\librustc_std_workspace_alloc-8572e8a98839f6d6.rlib" "C:\\Users\\AA\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libminiz_oxide-6e930372a69395c9.rlib" "C:\\Users\\AA\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libadler-ad696ea66c589e9d.rlib" "C:\\Users\\AA\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libunwind-0a3e7125dc6e7fef.rlib" "C:\\Users\\AA\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcfg_if-7d7ae0874b44dfcc.rlib" "C:\\Users\\AA\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\liblibc-2e82681b8e87518e.rlib" "C:\\Users\\AA\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\liballoc-5ed5a0d27d7423da.rlib" "C:\\Users\\AA\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\librustc_std_workspace_core-e970d604d303b37d.rlib" "C:\\Users\\AA\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcore-e73f27a013927059.rlib" "C:\\Users\\AA\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcompiler_builtins-fbb34b1faced902f.rlib" "avdevice.lib" "avfilter.lib" "avformat.lib" "avcodec.lib" "swresample.lib" "swscale.lib" "avutil.lib" "libx264.lib" "vpx.lib" "legacy_stdio_definitions.lib" "kernel32.lib" "advapi32.lib" "bcrypt.lib" "kernel32.lib" "ntdll.lib" "userenv.lib" "ws2_32.lib" "kernel32.lib" "ws2_32.lib" "kernel32.lib" "msvcrt.lib" "/NXCOMPAT" "/LIBPATH:C:\\Users\\AA\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "/OUT:C:\\Users\\AA\\Desktop\\rsmpeg-vcpkg-demo-master\\target\\debug\\deps\\rsmpeg_vcpkg_demo.exe" "/OPT:REF,NOICF" "/DEBUG" "/NATVIS:C:\\Users\\AA\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\intrinsic.natvis" "/NATVIS:C:\\Users\\AA\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\liballoc.natvis" "/NATVIS:C:\\Users\\AA\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\libcore.natvis" "/NATVIS:C:\\Users\\AA\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\libstd.natvis"
  = note: avformat.lib(tls_schannel.o) : error LNK2019: unresolved external symbol AcquireCredentialsHandleA referenced in function tls_open
          avformat.lib(tls_schannel.o) : error LNK2019: unresolved external symbol __imp_FreeCredentialsHandle referenced in function tls_close
          avformat.lib(tls_schannel.o) : error LNK2019: unresolved external symbol InitializeSecurityContextA referenced in function tls_close
          avformat.lib(tls_schannel.o) : error LNK2019: unresolved external symbol __imp_DeleteSecurityContext referenced in function tls_close
          avformat.lib(tls_schannel.o) : error LNK2019: unresolved external symbol __imp_ApplyControlToken referenced in function tls_close
          avformat.lib(tls_schannel.o) : error LNK2019: unresolved external symbol QueryContextAttributesA referenced in function tls_write
          avformat.lib(tls_schannel.o) : error LNK2019: unresolved external symbol FreeContextBuffer referenced in function tls_close
          avformat.lib(tls_schannel.o) : error LNK2019: unresolved external symbol EncryptMessage referenced in function tls_write
          avformat.lib(tls_schannel.o) : error LNK2019: unresolved external symbol DecryptMessage referenced in function tls_read
          avcodec.lib(mfenc.o) : error LNK2001: unresolved external symbol IID_ICodecAPI
          avcodec.lib(mfenc.o) : error LNK2001: unresolved external symbol IID_IMFMediaEventGenerator
          avcodec.lib(mf_utils.o) : error LNK2019: unresolved external symbol __imp_CoUninitialize referenced in function ff_free_mf
          avcodec.lib(mf_utils.o) : error LNK2019: unresolved external symbol __imp_CoInitializeEx referenced in function ff_instantiate_mf
          avcodec.lib(mf_utils.o) : error LNK2019: unresolved external symbol __imp_CoTaskMemFree referenced in function ff_instantiate_mf
          avcodec.lib(dxva2.o) : error LNK2001: unresolved external symbol __imp_CoTaskMemFree
          avcodec.lib(mf_utils.o) : error LNK2001: unresolved external symbol IID_IMFTransform
          avutil.lib(hwcontext_dxva2.o) : error LNK2019: unresolved external symbol __imp_GetDesktopWindow referenced in function dxva2_device_create
          C:\Users\AA\Desktop\rsmpeg-vcpkg-demo-master\target\debug\deps\rsmpeg_vcpkg_demo.exe : fatal error LNK1120: 16 unresolved externals

error: could not compile `rsmpeg-vcpkg-demo` (bin "rsmpeg-vcpkg-demo") due to previous error

C:\Users\AA\Desktop\rsmpeg-vcpkg-demo-master>
C:\Users\AA\Desktop\rsmpeg-vcpkg-demo-master>
C:\Users\AA\Desktop\rsmpeg-vcpkg-demo-master>cargo vcpkg --verbose build
vcpkg root is D:\vcpkg
    Fetching vcpkg
POST git-upload-pack (165 bytes)
From https://github.com/microsoft/vcpkg
 = [up to date]          master     -> origin/master
    Checkout rev 4a600e9
HEAD is now at 4a600e9fe [google-cloud-cpp] update to latest release (v2.14.0) (#33503)
-- stdout --
Using local portfile versions. To update the local portfiles, use `git pull`.
No packages need updating.

-- stderr --

ExitStatus(ExitStatus(0))
  Installing ffmpeg[x264,vpx]:x64-windows-static-md
Computing installation plan...
The following packages are already installed:
    ffmpeg[core,x264,vpx,swscale,swresample,gpl,avformat,avfilter,avdevice,avcodec]:x64-windows-static-md -> 5.1.2#7
ffmpeg:x64-windows-static-md is already installed
Total install time: 8.9 us
To use ffmpeg add the following to your CMake project:

    find_package(FFMPEG REQUIRED)
    target_include_directories(main PRIVATE ${FFMPEG_INCLUDE_DIRS})
    target_link_directories(main PRIVATE ${FFMPEG_LIBRARY_DIRS})
    target_link_libraries(main PRIVATE ${FFMPEG_LIBRARIES})

    Finished in 2.23s

C:\Users\AA\Desktop\rsmpeg-vcpkg-demo-master>
C:\Users\AA\Desktop\rsmpeg-vcpkg-demo-master>
C:\Users\AA\Desktop\rsmpeg-vcpkg-demo-master>cargo run
   Compiling rsmpeg-vcpkg-demo v0.1.0 (C:\Users\AA\Desktop\rsmpeg-vcpkg-demo-master)
error: linking with `link.exe` failed: exit code: 1120
  |
  = note: "C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\link.exe" "/NOLOGO" "C:\\Users\\AA\\AppData\\Local\\Temp\\rustcmIgHqY\\symbols.o" "C:\\Users\\AA\\Desktop\\rsmpeg-vcpkg-demo-master\\target\\debug\\deps\\rsmpeg_vcpkg_demo.14x009273zxltdzv.rcgu.o" "C:\\Users\\AA\\Desktop\\rsmpeg-vcpkg-demo-master\\target\\debug\\deps\\rsmpeg_vcpkg_demo.19ii64hvjq260mbw.rcgu.o" "C:\\Users\\AA\\Desktop\\rsmpeg-vcpkg-demo-master\\target\\debug\\deps\\rsmpeg_vcpkg_demo.265vt5w16atk6yqt.rcgu.o" "C:\\Users\\AA\\Desktop\\rsmpeg-vcpkg-demo-master\\target\\debug\\deps\\rsmpeg_vcpkg_demo.3hmyt0n3tadbqiqn.rcgu.o" "C:\\Users\\AA\\Desktop\\rsmpeg-vcpkg-demo-master\\target\\debug\\deps\\rsmpeg_vcpkg_demo.45z8zrhtcgwwtyrv.rcgu.o" "C:\\Users\\AA\\Desktop\\rsmpeg-vcpkg-demo-master\\target\\debug\\deps\\rsmpeg_vcpkg_demo.4amt6abzq6la6yx6.rcgu.o" "C:\\Users\\AA\\Desktop\\rsmpeg-vcpkg-demo-master\\target\\debug\\deps\\rsmpeg_vcpkg_demo.4n4c25295805ecq2.rcgu.o" "C:\\Users\\AA\\Desktop\\rsmpeg-vcpkg-demo-master\\target\\debug\\deps\\rsmpeg_vcpkg_demo.4petkjx744kw5ie5.rcgu.o" "C:\\Users\\AA\\Desktop\\rsmpeg-vcpkg-demo-master\\target\\debug\\deps\\rsmpeg_vcpkg_demo.5gpvfka59ser635i.rcgu.o" "C:\\Users\\AA\\Desktop\\rsmpeg-vcpkg-demo-master\\target\\debug\\deps\\rsmpeg_vcpkg_demo.pgoc93qhmn1nszl.rcgu.o" "C:\\Users\\AA\\Desktop\\rsmpeg-vcpkg-demo-master\\target\\debug\\deps\\rsmpeg_vcpkg_demo.ypkxbmvjwho5n88.rcgu.o" "C:\\Users\\AA\\Desktop\\rsmpeg-vcpkg-demo-master\\target\\debug\\deps\\rsmpeg_vcpkg_demo.3l5ane5fnmp7mtza.rcgu.o" "/LIBPATH:C:\\Users\\AA\\Desktop\\rsmpeg-vcpkg-demo-master\\target\\debug\\deps" "/LIBPATH:D:\\vcpkg\\installed\\x64-windows-static-md\\lib" "/LIBPATH:C:\\Users\\AA\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "C:\\Users\\AA\\Desktop\\rsmpeg-vcpkg-demo-master\\target\\debug\\deps\\librsmpeg-a432ad4d72d4fcbc.rlib" "C:\\Users\\AA\\Desktop\\rsmpeg-vcpkg-demo-master\\target\\debug\\deps\\libthiserror-203060b4736bfe63.rlib" "C:\\Users\\AA\\Desktop\\rsmpeg-vcpkg-demo-master\\target\\debug\\deps\\librusty_ffmpeg-e40ef72c28dc502c.rlib" "C:\\Users\\AA\\Desktop\\rsmpeg-vcpkg-demo-master\\target\\debug\\deps\\liblibc-d8595f7c09b145ad.rlib" "C:\\Users\\AA\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libstd-0f357f0f8e8eb48f.rlib" "C:\\Users\\AA\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libpanic_unwind-57325150de1d69ac.rlib" "C:\\Users\\AA\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\librustc_demangle-7a221d01d4c27fb2.rlib" "C:\\Users\\AA\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libstd_detect-7bffc6b402bc9229.rlib" "C:\\Users\\AA\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libhashbrown-3fd39796b57f4908.rlib" "C:\\Users\\AA\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\librustc_std_workspace_alloc-8572e8a98839f6d6.rlib" "C:\\Users\\AA\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libminiz_oxide-6e930372a69395c9.rlib" "C:\\Users\\AA\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libadler-ad696ea66c589e9d.rlib" "C:\\Users\\AA\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libunwind-0a3e7125dc6e7fef.rlib" "C:\\Users\\AA\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcfg_if-7d7ae0874b44dfcc.rlib" "C:\\Users\\AA\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\liblibc-2e82681b8e87518e.rlib" "C:\\Users\\AA\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\liballoc-5ed5a0d27d7423da.rlib" "C:\\Users\\AA\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\librustc_std_workspace_core-e970d604d303b37d.rlib" "C:\\Users\\AA\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcore-e73f27a013927059.rlib" "C:\\Users\\AA\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcompiler_builtins-fbb34b1faced902f.rlib" "avdevice.lib" "avfilter.lib" "avformat.lib" "avcodec.lib" "swresample.lib" "swscale.lib" "avutil.lib" "libx264.lib" "vpx.lib" "legacy_stdio_definitions.lib" "kernel32.lib" "advapi32.lib" "bcrypt.lib" "kernel32.lib" "ntdll.lib" "userenv.lib" "ws2_32.lib" "kernel32.lib" "ws2_32.lib" "kernel32.lib" "msvcrt.lib" "/NXCOMPAT" "/LIBPATH:C:\\Users\\AA\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "/OUT:C:\\Users\\AA\\Desktop\\rsmpeg-vcpkg-demo-master\\target\\debug\\deps\\rsmpeg_vcpkg_demo.exe" "/OPT:REF,NOICF" "/DEBUG" "/NATVIS:C:\\Users\\AA\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\intrinsic.natvis" "/NATVIS:C:\\Users\\AA\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\liballoc.natvis" "/NATVIS:C:\\Users\\AA\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\libcore.natvis" "/NATVIS:C:\\Users\\AA\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\libstd.natvis"
  = note: avformat.lib(tls_schannel.o) : error LNK2019: unresolved external symbol AcquireCredentialsHandleA referenced in function tls_open
          avformat.lib(tls_schannel.o) : error LNK2019: unresolved external symbol __imp_FreeCredentialsHandle referenced in function tls_close
          avformat.lib(tls_schannel.o) : error LNK2019: unresolved external symbol InitializeSecurityContextA referenced in function tls_close
          avformat.lib(tls_schannel.o) : error LNK2019: unresolved external symbol __imp_DeleteSecurityContext referenced in function tls_close
          avformat.lib(tls_schannel.o) : error LNK2019: unresolved external symbol __imp_ApplyControlToken referenced in function tls_close
          avformat.lib(tls_schannel.o) : error LNK2019: unresolved external symbol QueryContextAttributesA referenced in function tls_write
          avformat.lib(tls_schannel.o) : error LNK2019: unresolved external symbol FreeContextBuffer referenced in function tls_close
          avformat.lib(tls_schannel.o) : error LNK2019: unresolved external symbol EncryptMessage referenced in function tls_write
          avformat.lib(tls_schannel.o) : error LNK2019: unresolved external symbol DecryptMessage referenced in function tls_read
          avcodec.lib(mfenc.o) : error LNK2001: unresolved external symbol IID_ICodecAPI
          avcodec.lib(mfenc.o) : error LNK2001: unresolved external symbol IID_IMFMediaEventGenerator
          avcodec.lib(mf_utils.o) : error LNK2019: unresolved external symbol __imp_CoUninitialize referenced in function ff_free_mf
          avcodec.lib(mf_utils.o) : error LNK2019: unresolved external symbol __imp_CoInitializeEx referenced in function ff_instantiate_mf
          avcodec.lib(mf_utils.o) : error LNK2019: unresolved external symbol __imp_CoTaskMemFree referenced in function ff_instantiate_mf
          avcodec.lib(dxva2.o) : error LNK2001: unresolved external symbol __imp_CoTaskMemFree
          avcodec.lib(mf_utils.o) : error LNK2001: unresolved external symbol IID_IMFTransform
          avutil.lib(hwcontext_dxva2.o) : error LNK2019: unresolved external symbol __imp_GetDesktopWindow referenced in function dxva2_device_create
          C:\Users\AA\Desktop\rsmpeg-vcpkg-demo-master\target\debug\deps\rsmpeg_vcpkg_demo.exe : fatal error LNK1120: 16 unresolved externals

error: could not compile `rsmpeg-vcpkg-demo` (bin "rsmpeg-vcpkg-demo") due to previous error

**Comment by ldm0** [comment]
Please try this suggestion: https://github.com/larksuite/rsmpeg/pull/74#issuecomment-1085722495

**Comment by xxscloud5722** [comment]
It ran successfully. I modified the configuration as follows

[source.crates-io]
replace-with = 'rsproxy-sparse'
[source.rsproxy]
registry = "https://rsproxy.cn/crates.io-index"
[source.rsproxy-sparse]
registry = "sparse+https://rsproxy.cn/index/"
[registries.rsproxy]
index = "https://rsproxy.cn/crates.io-index"
[net]
git-fetch-with-cli = true

[target.x86_64-pc-windows-msvc]
rustflags = [
    "-C", "link-arg=Mfplat.lib",
    "-C", "link-arg=Strmiids.lib",
    "-C", "link-arg=Mfuuid.lib",
    "-C", "link-arg=Bcrypt.lib",
    "-C", "link-arg=Secur32.lib",
    "-C", "link-arg=Ole32.lib",
    "-C", "link-arg=User32.lib"
]
