### ISSUE TITLE
compile "rsmpeg-vcpkg-demo" error on windows

### ISSUE THREAD

**Issue by osenberg-x** [larksuite/rsmpeg#123]
error: failed to run custom build command for `rusty_ffmpeg v0.13.1+ffmpeg.6.0`

![image](https://github.com/larksuite/rsmpeg/assets/42266214/668b5a42-07f5-4093-aec7-73198c252082)

what should i do?

**Comment by ldm0** [comment]
Please post the full error report, the screenshot is missing important information.

**Comment by osenberg-x** [comment]
@ldm0 this is full output.
`   Compiling windows_x86_64_msvc v0.48.5
   Compiling proc-macro2 v1.0.66
   Compiling unicode-ident v1.0.11
   Compiling glob v0.3.1
   Compiling winapi v0.3.9
   Compiling libc v0.2.147
   Compiling rustix v0.38.11
   Compiling syn v1.0.109
   Compiling regex-syntax v0.7.5
   Compiling memchr v2.6.3
   Compiling clang-sys v1.6.1
   Compiling minimal-lexical v0.2.1
   Compiling bitflags v2.4.0
   Compiling regex-automata v0.3.8
   Compiling windows-targets v0.48.5
   Compiling nom v7.1.3
   Compiling quote v1.0.33
   Compiling windows-sys v0.48.0
   Compiling bindgen v0.64.0
   Compiling either v1.9.0
   Compiling libloading v0.7.4
   Compiling camino v1.1.6
   Compiling once_cell v1.18.0
   Compiling regex v1.9.5
   Compiling cexpr v0.6.0
   Compiling rustc-hash v1.1.0
   Compiling shlex v1.1.0
   Compiling lazycell v1.3.0
   Compiling bitflags v1.3.2
   Compiling lazy_static v1.4.0
   Compiling peeking_take_while v0.1.2
   Compiling log v0.4.20
   Compiling vcpkg v0.2.15
   Compiling syn v2.0.31
   Compiling errno v0.3.3
   Compiling home v0.5.5
   Compiling paste v1.0.14
   Compiling which v4.4.2
   Compiling thiserror v1.0.48
   Compiling thiserror-impl v1.0.48
   Compiling rusty_ffmpeg v0.13.1+ffmpeg.6.0
error: failed to run custom build command for `rusty_ffmpeg v0.13.1+ffmpeg.6.0`

Caused by:
  process didn't exit successfully: `E:\ws\rsmpeg-vcpkg-demo\target\debug\build\rusty_ffmpeg-791ae24289103844\build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-env-changed=DOCS_RS
  cargo:rerun-if-env-changed=OUT_DIR
  cargo:rerun-if-env-changed=FFMPEG_INCLUDE_DIR
  cargo:rerun-if-env-changed=FFMPEG_DLL_PATH
  cargo:rerun-if-env-changed=FFMPEG_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=FFMPEG_LIBS_DIR
  cargo:rerun-if-env-changed=FFMPEG_BINDING_PATH
  cargo:rustc-link-search=native=D:\env\vcpkg\installed\x64-windows-static-md\lib
  cargo:rustc-link-lib=avdevice
  cargo:rustc-link-lib=avfilter
  cargo:rustc-link-lib=avformat
  cargo:rustc-link-lib=avcodec
  cargo:rustc-link-lib=swresample
  cargo:rustc-link-lib=swscale
  cargo:rustc-link-lib=avutil
  cargo:rustc-link-lib=x265-static
  cargo:rustc-link-lib=vpx

  --- stderr
  thread 'main' panicked at 'Unable to find libclang: "couldn't find any valid shared libraries matching: ['clang.dll', 'libclang.dll'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [])"', C:\Users\osenb\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bindgen-0.64.0\./lib.rs:2393:31
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`

**Comment by ldm0** [comment]
> @ldm0 this is full output.

> thread 'main' panicked at 'Unable to find libclang: "couldn't find any valid shared libraries matching: ['clang.dll', 'libclang.dll'], set the LIBCLANG_PATH environment variable to a path where one of these files can be found (invalid: [])"', C:\Users\osenb.cargo\registry\src\index.crates.io-6f17d22bba15001f\bindgen-0.64.0./lib.rs:2393:31
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace`

The build script cannot find the libclang.dll to generate rust bindings for FFmpeg header files. You can install Clang [`here`](https://github.com/llvm/llvm-project/releases/download/llvmorg-17.0.1/LLVM-17.0.1-win64.exe) and check again.

**Comment by osenberg-x** [comment]
@ldm0 thinks，i have solved this problem, and success to run example
