### ISSUE TITLE
Can you provide the decoding of MP4 AVCC format?

### ISSUE THREAD

**Issue by xxscloud5722** [larksuite/rsmpeg#124]
Can you provide the decoding of MP4 AVCC format?
I'm really 'CPU is burning out'

**Comment by xxscloud5722** [comment]
CPU (brain) is burning out

**Comment by ldm0** [comment]
You can play with the examples in `tests` folder, especially. <https://github.com/larksuite/rsmpeg/blob/master/tests/decode_video.rs>.

**Comment by xxscloud5722** [comment]
First of all, I really appreciate your reply. What I need is MP4 AVCC, DEMO is MPG and other formats. Specific reference: https://stackoverflow.com/questions/24884827/possible-locations-for-sequence-picture-parameter-sets-for -h-264-stream/24890903#24890903

**Comment by xxscloud5722** [comment]
It is estimated that only calling the underlying API can solve the problem
