### ISSUE TITLE
cargo run error

### ISSUE THREAD

**Issue by lamhai1401** [larksuite/rsmpeg#17]
I'm new to rust.
I ran cargo build like in the resp example.
Could you tell me why i had this error and how to fix.
Thanks in advance!

<img width="858" alt="Screen Shot 2021-05-25 at 16 33 49" src="https://user-images.githubusercontent.com/31619361/119475083-01917580-bd77-11eb-8e9f-ca383502ca68.png">

**Comment by ldm0** [comment]
Thanks for the bug report. As the README states: `Supported FFmpeg version is 4.0-4.4.`. I think you are using FFmpeg's master, which removes the `avpicture-related` functions (and even more). I suggest you checkout to the `release/4.4` branch of FFmpeg and compile.

**Comment by ldm0** [comment]
Feel free to reopen this if you can't get it works.

**Comment by lamhai1401** [comment]
Thank you for your quick response. But i installed ffmpeg with these steps: 
Step1:  Running bash mac_ffmpeg.rs in your utils folder
Step2: export FFMPEG_PKG_CONFIG_PATH=xxx/tmp/ffmpeg_build/lib/pkgconfig
Step3: cargo run
And still have that error above. I'm using mac os big sur 11.4.

**Comment by ldm0** [comment]
@lamhai1401  Ah I think I know why.... Try `cargo clean`, then recompile it. The build cache doesn't invalidates when you changed the C libs.

**Comment by lamhai1401** [comment]
> @lamhai1401 Ah I think I know why.... Try `cargo clean`, then recompile it. The build cache doesn't get invalidated when you change the C libs.

I try to run it in my ubuntu (20.04), ffmpeg `version 4.3` with these steps above, i got a missing list lib, it's worked when i install all of it (apt install xxx).
So i change the branch `release/4.4` -> `release/4.3` in your `mac_ffmpeg.rs`, reinstall it and run `cargo clean`. It's worked!!
Thank for your response :+1:. Amazing!

**Comment by ldm0** [comment]
@lamhai1401 After #21 ，you can run `rsmpeg` with `FFmpeg`'s latest master!
