### ISSUE TITLE
cannot assign to data in dereference of `rsmpeg::avutil::AVFrame`

### ISSUE THREAD

**Issue by aegroto** [larksuite/rsmpeg#186]
Is there a way to modify arbitrary fields of the AVFrame struct? For instance, I would like to assign a value to the *opaque* pointer:

```
        let mut avframe = rsmpeg::avutil::AVFrame::new();
        avframe.opaque = std::ptr::null_mut();
```

But the compiler consider this as a dereference and therefore would require DerefMut to be implemented.

What's the most idiomatic way to modify data not considered in the wrapper struct rsmpeg::avutil::AVFrame but that are part of the underlying C struct?

**Comment by ldm0** [comment]
You can try [UnsafeDerefMut](https://docs.rs/rsmpeg/latest/rsmpeg/trait.UnsafeDerefMut.html).

**Comment by aegroto** [comment]
Thanks, that's exactly what I was looking for! I have another doubt, are such data transmitted from the encoder to the decoder? I am facing a weird issue, it seems like any modification I make in the AVFrame I send to the encoding context is then missing in the received AVFrame from the decoding context. Is there any specific rule I have to follow to transmit arbitrary data or am I be doing something wrong maybe?
