### ISSUE TITLE
how to use rsmpeg

### ISSUE THREAD

**Issue by phial3** [larksuite/rsmpeg#191]
macOS m2 install ffmpeg 7.0 by brew: `/opt/homebrew/opt/ffmpeg`

in project `Cargo.toml`
```toml
rsmpeg = "0.15"
```

<img width="503" alt="image" src="https://github.com/user-attachments/assets/5052511b-a9e3-4454-abf9-252d589f59bf">

**Comment by ldm0** [comment]
Thank's for reporting.

I am unable to reproduce this issue. Could you try importing `rsmpeg` like this:

```
rsmpeg = { git = "https://github.com/larksuite/rsmpeg", branch = "master", features = ["ffmpeg7", "link_system_ffmpeg"] }
```

Let me know if the issue still persists.
