### ISSUE TITLE
How do I associate multiple inputs in the filter

### ISSUE THREAD

**Issue by imxood** [larksuite/rsmpeg#56]
I want to achieve split screen effect, at the beginning, I will associate multiple inputs in the filter.
but I can't do it, because of the wrong
```rust
outputs.next = video1_outputs.as_mut_ptr();

cannot assign to data in a dereference of `rsmpeg::avfilter::AVFilterInOut`
trait `DerefMut` is required to modify through a dereference, but it is not implemented for `rsmpeg::avfilter::AVFilterInOut`
```

the main code:
```rust
// 创建buffer, 用于接收输入
let buffer_src = AVFilter::get_by_name(cstr!("buffer")).unwrap();

// video0: 创建 filter 上下文, 关联 输入的 buffer
let mut buffer_src_context =
  filter_graph.create_filter_context(&buffer_src, cstr!("video0"), Some(args))?;
// video0: 分配 filter 的输入, 关联 创建的 filter 上下文
let mut outputs = AVFilterInOut::new(cstr!("video0"), &mut buffer_src_context, 0);

// video1: 创建 filter 上下文, 关联 输入的 buffer
let mut buffer_src_context =
  filter_graph.create_filter_context(&buffer_src, cstr!("video1"), Some(args))?;
// video1: 分配 filter 的输入, 关联 创建的 filter 上下文
let mut video1_outputs = AVFilterInOut::new(cstr!("video1"), &mut buffer_src_context, 0);

// 关联 多个输入
outputs.next = video1_outputs.as_mut_ptr();
// outputs.next = video1_outputs.into_raw().as_ptr();
```

in rsmpeg:
wrap!(AVFilterInOut: ffi::AVFilterInOut);
this is:
wrap_pure!(($name): $ffi_type $(,$attach: $attach_type = $attach_default)*);
and this implements
```rust
pub fn as_mut_ptr(&mut self) -> *mut $ffi_type {
   self.something_should_not_be_touched_directly.as_ptr()
}
```
but why can't it --> outputs.next = video1_outputs.as_mut_ptr();

**Comment by ldm0** [comment]
By design, all wrappers doesn't implement the `DerefMut` by default because the "safety" restriction. But you will find it implements `UnsafeDerefMut`, which makes deref_mut() still unsafe, and it's used internally. I think exporting it is a good option. Then you can do:
```rust
unsafe { outputs.deref_mut().next = video1_outputs.as_mut_ptr(); }
```

**Comment by ldm0** [comment]
Could you check it with the current master?

**Comment by imxood** [comment]
Thanks for your great help~
I am testing it.

**Comment by imxood** [comment]
```rust
unsafe {
  outputs.deref_mut().next = video1_outputs.as_mut_ptr();
}
```
only use the code, no "use rsmpeg::UnsafeDerefMut;"
it build ok, I will try to implement my function

**Comment by imxood** [comment]
I implemented the effect of multi frame splicing
![image](https://user-images.githubusercontent.com/14890680/128271025-4fe7b3fe-63f4-485d-8708-dd008d86b814.png)
it is implemented in C language.
![image](https://user-images.githubusercontent.com/14890680/128270755-52096eb3-23a6-4f28-af47-e41c90994d34.png)

however I don't know how to express below code in rsmpeg:
```rust
AVFilterInOut *filterIn = NULL;
AVFilterInOut *filterOut = NULL;
...
ret = avfilter_graph_parse_ptr(graph, filters_desc, &filterIn, &filterOut, NULL);
```
here filterIn filterOut are Null, how to implement it in rsmpeg?

**Comment by ldm0** [comment]
> @ldm0
> I implemented the effect of multi frame splicing
> ![image](https://user-images.githubusercontent.com/14890680/128271025-4fe7b3fe-63f4-485d-8708-dd008d86b814.png)
> it is implemented in C language.
> ![image](https://user-images.githubusercontent.com/14890680/128270755-52096eb3-23a6-4f28-af47-e41c90994d34.png)
> 
> however I don't know how to express below code in rsmpeg:
> 
> ```rust
> AVFilterInOut *filterIn = NULL;
> AVFilterInOut *filterOut = NULL;
> ```
> 
> here filterIn filterOut are Null, how to implement it in rsmpeg?

Strange. I never thought users could create a filter graph with no input and output. I'll change this function's signature.

**Comment by imxood** [comment]
@ldm0 为了实现这个效果, 各种办法都试了, 幸好成功了, 上面这办法不需要手动实现 filter ctx, 通过 graph parse 的.

![image](https://user-images.githubusercontent.com/14890680/128289194-57fe8eaf-2334-4c29-a552-bebfb7aa9e88.png)

多个 buffer 和单个 buffersink 定义在 filter spec 中, 在 graph parse 后, 可以从 graph 中拿到 filter ctx, 就可以send frame and get frame.

**Comment by ldm0** [comment]
> @ldm0 为了实现这个效果, 各种办法都试了, 幸好成功了, 上面这办法不需要手动实现 filter ctx, 通过 graph parse 的.
> 
> ![image](https://user-images.githubusercontent.com/14890680/128289194-57fe8eaf-2334-4c29-a552-bebfb7aa9e88.png)
> 
> 多个 buffer 和单个 buffersink 定义在 filter spec 中, 在 graph parse 后, 可以从 graph 中拿到 filter ctx, 就可以send frame and get frame.

原来还有这种用法么（，等会加个api包装一下`avfilter_graph_get_filter`
