### ISSUE TITLE
why not export "mod shared"?

### ISSUE THREAD

**Issue by imxood** [larksuite/rsmpeg#59]
` mod shared; ` in src/lib.rs
why isn't it ` pub mod shared; `

sometimes, i need use ffi function, so i need write custom safe function to call unsafe ffi function.

for example:

if there is ` pub mod shared; ` I can use ` rsmpeg::shared::{RetUpgrade, RsmpegPointerUpgrade};`

![image](https://user-images.githubusercontent.com/14890680/128288831-e769affb-10b0-4e94-9a12-a76caec2ecd5.png)

**Comment by ldm0** [comment]
The reason I haven't export `mod shared` is that I think it's not general enough to be used in other crates. These traits are not  self-explained enough, which means users need to read the code carefully to understand what they do. And they aren't stable, maybe changed after times. If you really want to use them, you can copy these traits into your own project.

**Comment by imxood** [comment]
> The reason I haven't export `mod shared` is that I think it's not general enough to be used in other crates. These traits are not self-explained enough, which means users need to read the code carefully to understand what they do. And they aren't stable, maybe changed after times. If you really want to use them, you can copy these traits into your own project.

这几个 upgrade 非常好用, 配合 Result ? 的用法, 和anyhow一起, 非常简单和方便的, 代码看着也很美观
导出 shared mod 是很不错的选择
