### ISSUE TITLE
fatal error LNK1181: cannot open input file 'bin.lib' in win10

### ISSUE THREAD

**Issue by gowuliao** [larksuite/rsmpeg#70]
Run “cargo build” is ok
The following error occurred when running "cargo run --example shadertoy"

 ..."C:\\Users\\w\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcompiler_builtins-0f3806ca1d72c7be.rlib" "bin.lib" "opengl32.lib" "gdi32.lib" "user32.lib" "shell32.lib" "advapi32.lib" "cfgmgr32.lib" "credui.lib" "gdi32.lib" "kernel32.lib" "msimg32.lib" "opengl32.lib" "secur32.lib" "user32.lib" "winspool.lib" "kernel32.lib" "ws2_32.lib" "advapi32.lib" "userenv.lib" "kernel32.lib" "libcmt.lib" "/NXCOMPAT" "/LIBPATH:C:\\Users\\w\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "/OUT:C:\\other\\rsmpeg\\target\\debug\\examples\\shadertoy.exe" "/OPT:REF,NOICF" "/DEBUG" "/NATVIS:C:\\Users\\w\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\intrinsic.natvis" "/NATVIS:C:\\Users\\w\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\liballoc.natvis" "/NATVIS:C:\\Users\\w\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\libcore.natvis" "/NATVIS:C:\\Users\\w\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\libstd.natvis"
  = note: LINK : fatal error LNK1181: cannot open input file 'bin.lib'

error: aborting due to previous error

error: could not compile `rsmpeg`

Caused by:
  process didn't exit successfully: `rustc --crate-name shadertoy --edition=2018 examples\shadertoy.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C embed-bitcode=no -C debuginfo=2 -C metadata=a6c024520f0f1717 --out-dir C:\other\rsmpeg\target\debug\examples -C incremental=C:\other\rsmpeg\target\debug\incremental -L dependency=C:\other\rsmpeg\target\debug\deps --extern anyhow=C:\other\rsmpeg\target\debug\deps\libanyhow-aac36a585e39dec0.rlib --extern cstr=C:\other\rsmpeg\target\debug\deps\cstr-bd7a940b0e069e57.dll --extern env_logger=C:\other\rsmpeg\target\debug\deps\libenv_logger-4d58fb072faef0cd.rlib --extern gl=C:\other\rsmpeg\target\debug\deps\libgl-a6a63575228fb3f7.rlib --extern glfw=C:\other\rsmpeg\target\debug\deps\libglfw-0dec44ffa560978f.rlib --extern libc=C:\other\rsmpeg\target\debug\deps\liblibc-40c4f9b1ccf0e38b.rlib --extern log=C:\other\rsmpeg\target\debug\deps\liblog-e0d660174d079955.rlib --extern once_cell=C:\other\rsmpeg\target\debug\deps\libonce_cell-74b4d97d099287d3.rlib --extern paste=C:\other\rsmpeg\target\debug\deps\paste-c0de4a0431d89d62.dll --extern rsmpeg=C:\other\rsmpeg\target\debug\deps\librsmpeg-c8af3314532851e3.rlib --extern rusty_ffmpeg=C:\other\rsmpeg\target\debug\deps\librusty_ffmpeg-b2d3c1caf20494e4.rlib --extern tempdir=C:\other\rsmpeg\target\debug\deps\libtempdir-79b947ca5a5a7811.rlib --extern thiserror=C:\other\rsmpeg\target\debug\deps\libthiserror-c66c5cfd5369a7cf.rlib -Ctarget-feature=+crt-static -L native=C:\other\rsmpeg\target\debug\build\glfw-sys-d6813c780a0799e8\out\lib -L native=C:\other\vcpkg\packages\ffmpeg_x64-windows` (exit code: 1)

**Comment by ldm0** [comment]
I have never seen the "bin.lib" before, have you tried cargo clean and rebuliding the project?

If that doesn't help, please post the output of the `rusty_ffmpeg`'s build script in it's `OUT_DIR`. https://doc.rust-lang.org/cargo/reference/build-scripts.html#outputs-of-the-build-script

**Comment by ldm0** [comment]
Feel free to reopen this issue if suggestions above doesn't help. :-)

**Comment by FallingSnow** [comment]
Hmm, I'm running into this too. I tried `cargo clean` before hand but the error persists. (I changed the name of my crate to `project` in the logs below.)
```rust
warning: `project` (lib) generated 11 warnings (run `cargo fix --lib -p project` to apply 9 suggestions)
error: linking with `link.exe` failed: exit code: 1181
  |
  = note: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.44.35207\\bin\\HostX64\\x64\\link.exe" "/NOLOGO" "C:\\Users\\Ayrton\\AppData\\Local\\Temp\\rustc4LOKUx\\symbols.o" "<182 object files omitted>" "C:\\Users\\Ayrton\\Coding\\project\\target\\debug\\deps/{libthread_priority-5ed50036407c20aa.rlib,libuniversalis_vm2-d56a08d3383c778f.rlib,libsoftbuffer-574910963d2a2b95.rlib,libwindows_sys-4891f6d2a4cede9a.rlib,libkanal-5e0865e2b5898937.rlib,libthiserror-0d5ff44762ed1c57.rlib,libenigo-7be4e9432e0d6ca6.rlib,libwindows-8fae419c74c86f9c.rlib,libwindows_core-5ae1f15760a14785.rlib,libwindows_result-bd15215a60e8611e.rlib,libreed_solomon_simd-10a94398e1808b7d.rlib,libbytemuck-b43ae1a69914d1c8.rlib,libfixedbitset-2ac25c5af14f1f15.rlib,libnvidia_video_codec_sdk-467738fb981fc38c.rlib,libcudarc-dfc50a01a4fcd13d.rlib,liblibloading-1c510d8accfaca93.rlib,libwinit-08f2a3f013da48be.rlib,libunicode_segmentation-88beeb0e508b432b.rlib,libbitflags-83542f4d6e79e6c7.rlib,libsmol_str-8dddbc583aaaa6e8.rlib,libcursor_icon-e80ff96fb6b597ec.rlib,libdpi-f6390b86bb62b2a3.rlib,libraw_window_handle-582f85daf242c719.rlib,librsmpeg-7b50c64c1c5c1f97.rlib,libthiserror-64852aca8097a268.rlib,libbon-3da7f3fd6255a798.rlib,librusty_ffmpeg-cda6dff32c59a3be.rlib,libdeadpool-663eddbe6be6cfa3.rlib,libnum_cpus-a55261556753bb39.rlib,libdeadpool_runtime-57fec233cae74772.rlib,libdxgcap2-3fd8d535ad147d1d.rlib,libwindows-6929c45d37a2fa31.rlib,libwindows_collections-76c5c0ee2cb4aa0e.rlib,libwindows_core-5d5abc9fb66c815f.rlib,libwindows_strings-116d3baecd4cab31.rlib,libwindows_result-9907d22de7a1e412.rlib,libwindows_link-1fc142521e6ae385.rlib,libtracing_subscriber-05a3fa07136ced94.rlib,libnu_ansi_term-1633175ffeaeff4c.rlib,liboverload-712aa2f2bab2025b.rlib,libwinapi-a9e4e7c4e87b1da8.rlib,libsharded_slab-5ace9a378ebe67f3.rlib,liblazy_static-2cdd0a04ee65465c.rlib,libmatchers-6206dc8a6ccf0617.rlib,libregex_automata-04dd041a37ac9f44.rlib,libregex_syntax-33dee69e984da8c2.rlib,libregex-cbac625aa4d1ab4a.rlib,libregex_automata-796b9809b673c724.rlib,libregex_syntax-9a951cf9c4979b48.rlib,libthread_local-71e62223cebda880.rlib,libtracing_log-9bba02899add65ad.rlib,liblog-b3c8314dd6e81163.rlib,libtokio_util-686039ef41ba81c5.rlib,libfutures_core-a61458ae84287cf8.rlib,libfutures_sink-5d8c16574179a302.rlib,libtokio-a396120bb2454e65.rlib,libsocket2-1dc80e568e894fee.rlib,libmio-d3e4496ff13a67ff.rlib,libwindows_sys-db178aa747cb92f9.rlib,libtracing-507b5c2b17c897db.rlib,libtracing_core-050cc182b4512ead.rlib,libonce_cell-478e955731f18bda.rlib,libparking_lot-85adf43a1c29c64f.rlib,libparking_lot_core-5bc6cad586002de7.rlib,libwindows_targets-745782fe188b4364.rlib,libcfg_if-c5f9bd3c5375f63c.rlib,libsmallvec-5cccd924df3f9ea9.rlib,liblock_api-a14476097fd30385.rlib,libscopeguard-47d34930978dba02.rlib,libpin_project_lite-e83d873136beed13.rlib,libbytes-ab8cc6aa20cb975c.rlib}.rlib" "<sysroot>\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib/{libstd-*,libpanic_unwind-*,libwindows_targets-*,librustc_demangle-*,libstd_detect-*,libhashbrown-*,librustc_std_workspace_alloc-*,libunwind-*,libcfg_if-*,liballoc-*,librustc_std_workspace_core-*,libcore-*,libcompiler_builtins-*}.rlib" "C:\\Users\\Ayrton\\.cargo\\registry\\src\\index.crates.io-1949cf8c6b5b557f\\windows_x86_64_msvc-0.52.6\\lib\\windows.0.52.0.lib" "C:\\Users\\Ayrton\\.cargo\\registry\\src\\index.crates.io-1949cf8c6b5b557f\\windows_x86_64_msvc-0.52.6\\lib\\windows.0.52.0.lib" "C:\\Users\\Ayrton\\.cargo\\registry\\src\\index.crates.io-1949cf8c6b5b557f\\windows_x86_64_msvc-0.52.6\\lib\\windows.0.52.0.lib" "C:\\Users\\Ayrton\\.cargo\\registry\\src\\index.crates.io-1949cf8c6b5b557f\\windows_x86_64_msvc-0.52.6\\lib\\windows.0.52.0.lib" "C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v12.6\\lib/x64\\nvencodeapi.lib" "C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v12.6\\lib/x64\\nvcuvid.lib" "C:\\Users\\Ayrton\\.cargo\\registry\\src\\index.crates.io-1949cf8c6b5b557f\\windows_x86_64_msvc-0.52.6\\lib\\windows.0.52.0.lib" "bin.lib" "advapi32.lib" "cfgmgr32.lib" "gdi32.lib" "kernel32.lib" "msimg32.lib" "opengl32.lib" "user32.lib" "winspool.lib" "C:\\Users\\Ayrton\\.cargo\\registry\\src\\index.crates.io-1949cf8c6b5b557f\\windows_x86_64_msvc-0.52.6\\lib\\windows.0.52.0.lib" "C:\\Users\\Ayrton\\.cargo\\registry\\src\\index.crates.io-1949cf8c6b5b557f\\windows_x86_64_msvc-0.52.6\\lib\\windows.0.52.0.lib" "kernel32.lib" "kernel32.lib" "ntdll.lib" "userenv.lib" "ws2_32.lib" "dbghelp.lib" "/defaultlib:msvcrt" "/NXCOMPAT" "/LIBPATH:C:\\Users\\Ayrton\\.cargo\\registry\\src\\index.crates.io-1949cf8c6b5b557f\\windows_x86_64_msvc-0.52.6\\lib" "/LIBPATH:C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v12.6\\lib/x64" "/LIBPATH:C:\\Users\\Ayrton\\Coding\\project\\../../bin/ffmpeg" "/OUT:C:\\Users\\Ayrton\\Coding\\project\\target\\debug\\examples\\full_continous_pipeline.exe" "/OPT:REF,NOICF" "/DEBUG" "/PDBALTPATH:%_PDB%" "/NATVIS:<sysroot>\\lib\\rustlib\\etc\\intrinsic.natvis" "/NATVIS:<sysroot>\\lib\\rustlib\\etc\\liballoc.natvis" "/NATVIS:<sysroot>\\lib\\rustlib\\etc\\libcore.natvis" "/NATVIS:<sysroot>\\lib\\rustlib\\etc\\libstd.natvis" "/NATVIS:C:\\Users\\Ayrton\\AppData\\Local\\Temp\\rustc4LOKUx\\full_continous_pipeline-0.natvis" "/NATVIS:C:\\Users\\Ayrton\\AppData\\Local\\Temp\\rustc4LOKUx\\full_continous_pipeline-1.natvis" "/NATVIS:C:\\Users\\Ayrton\\AppData\\Local\\Temp\\rustc4LOKUx\\full_continous_pipeline-2.natvis"
  = note: some arguments are omitted. use `--verbose` to show all linker arguments
  = note: LINK : fatal error LNK1181: cannot open input file 'bin.lib'␍
```

Output of `rusty_ffmpeg` build script.
```rust
cargo:rerun-if-env-changed=DOCS_RS
cargo:rerun-if-env-changed=OUT_DIR
cargo:rerun-if-env-changed=FFMPEG_INCLUDE_DIR
cargo:rerun-if-env-changed=FFMPEG_DLL_PATH
cargo:rerun-if-env-changed=FFMPEG_PKG_CONFIG_PATH
cargo:rerun-if-env-changed=FFMPEG_LIBS_DIR
cargo:rerun-if-env-changed=FFMPEG_BINDING_PATH
cargo:rustc-link-lib=dylib=bin
cargo:rustc-link-search=native=C:\Users\Ayrton\Coding\project\../../bin/ffmpeg
```
