### ISSUE TITLE
relocation R_X86_64_32 against symbol `ff_pw_32' can not be used when making a shared object; recompile with -fPIC

### ISSUE THREAD

**Issue by zhouruisong** [larksuite/rsmpeg#72]
本人rust 新手，在执行test的时候直接报一大堆错误
执行test之前已经先执行
` zsh utils/linux_ffmpeg.rs `
成功编译ffmpeg4.4版本，并且在tmp下生成了相关的库和头文件
运行test之前先执行了 
`export FFMPEG_PKG_CONFIG_PATH=/root/go/src/rsmpeg/tmp/ffmpeg_build/lib/pkgconfig`
 然后执行了 
` cargo test --test transcoding`
报错如下图

![image](https://user-images.githubusercontent.com/18162573/153183069-e1fb3613-aab5-40c8-92e4-7d072cf2981c.png)

**Comment by ldm0** [comment]
Ref: https://stackoverflow.com/questions/43367427/32-bit-absolute-addresses-no-longer-allowed-in-x86-64-linux

Please try adding `--enable-pic` into the `linux_ffmpeg.rs`?.
e.g.
```git
    Command::new("./configure")
        .arg(format!("--prefix={}/ffmpeg_build", tmp_path))
        .arg("--enable-gpl")
        // .arg("--enable-libass")
        // .arg("--enable-libfdk-aac")
        // .arg("--enable-libfreetype")
        .arg("--enable-libmp3lame")
        // .arg("--enable-libopus")
        // .arg("--enable-libvorbis")
        .arg("--enable-libvpx")
        .arg("--enable-libx264")
        // .arg("--enable-libx265")
        .arg("--disable-programs")
        .arg("--enable-nonfree")

        .arg("--enable-pic")

        .spawn()?
        .wait()?;

```

**Comment by ldm0** [comment]
If you still encounter this error, feel free to reopen this issue. :-)
