### ISSUE TITLE
rsmpeg v0.7.1 编译报错

### ISSUE THREAD

**Issue by sunxingsong** [larksuite/rsmpeg#79]
我在使用 rsmpeg v0.7.1  时候出现了一些错误.
![image](https://user-images.githubusercontent.com/6611189/162362744-2bcb7915-0076-478f-a8ea-fa90628dff15.png)

**Comment by sunxingsong** [comment]
应该是需要依赖 rusty_ffmpeg v0.8.0

**Comment by ldm0** [comment]
是在用FFmpeg 5.0么，0.7.1不支持5.0，最新的master是支持的

**Comment by ldm0** [comment]
试试 rsmpeg = { git = "https://github.com/larksuite/rsmpeg", branch = "master" }

**Comment by sunxingsong** [comment]
直接用的master好用了， 我以为0.7.1 就是master， 感谢。
