### ISSUE TITLE
target cross platform support

### ISSUE THREAD

**Issue by lattice0** [larksuite/rsmpeg#81]
hello, it looks like you do not support different targets, like, I want to support cross compiling for linux, android, windows, etc, so, currently I'm doing

```
FFMPEG_LIBS_DIR=/home/dev/project/deps/ffmpeg/build/linux/x86_64/lib/pkgconfig \
FFMPEG_INCLUDE_DIR=/home/dev/project/deps/ffmpeg/build/linux/x86_64/include
```

I could set each one before building, but wouldn't it be better to make something more automated where it can support all types?

**Comment by ldm0** [comment]
Writing xtask scripts is always suggested if you have complex environment variables set for rust project. If you find it complex, hardcode the env var in project build script(cfged by target_os) should also work.

> but wouldn't it be better to make something more automated where it can support all types?

Providing env vars for rsmpeg build script is the best option I can think of. Any suggestion?

**Comment by ldm0** [comment]
Feel free to reopen this issue if it doesn't meet your expection. :-)
