### ISSUE TITLE
mutable `data_mut` and `linesize_mut` 

### ISSUE THREAD

**Issue by lattice0** [larksuite/rsmpeg#82]
at https://github.com/larksuite/rsmpeg/blob/master/src/avutil/frame.rs#L76, these two

```
    pub fn data_mut(&mut self) -> &mut [*mut u8; 8] {
        unsafe { &mut self.deref_mut().data }
    }

    pub fn linesize_mut(&mut self) -> &mut [libc::c_int; 8] {
        unsafe { &mut self.deref_mut().linesize }
    }
```

are mutable. Can I do versions for `&self`? Also, why it returns `&mut [*mut u8; 8]` and not `&mut [&mut[u8]]`? I have to rely on usafe outside of the library to do `std::slice::from_raw_parts` (is it even safe?)

**Comment by ldm0** [comment]
Size of AVFrame.data[0] is not well-defined by FFmpeg. Due to this limitation, there is no way to exposed the data safely(as slice).

**Comment by ldm0** [comment]
> Can I do versions for &self?

`&AVFrame` derefs to `&ffi::AVFrame`, so you can direct access the data and line_size by `frame.data` and `frame.line_size`. Ref https://docs.rs/rsmpeg/0.8.0/rsmpeg/ffi/struct.AVFrame.html#structfield.data

**Comment by ldm0** [comment]
Feel free to reopen this issue if it doesn't work. :-)
