### ISSUE TITLE
请问怎么才能生成Fragmented MP4

### ISSUE THREAD

**Issue by lyaf** [larksuite/rsmpeg#89]
想生成FMP4 方便在游览器上观看：
实现类似的效果:
`ffmpeg.exe -i test.264  -f mp4 -movflags frag_keyframe+empty_moov output.mp4`
我看其他教程，用C语言时候，写入文件格式头信息的时候设置AVDictionary结构体
```
AVDictionary *opts = NULL;
av_dict_set(&opts, "movflags", "frag_keyframe+empty_moov", 0);
avformat_write_header(o_fmt_ctx, &opts);
av_dict_free(&opts);
```
但是，我看了源码rsmpeg的话默认设置null
```
pub fn write_header(&mut self) -> Result<()> {
        unsafe { ffi::avformat_write_header(self.as_mut_ptr(), ptr::null_mut()) }
            .upgrade()
            .map_err(RsmpegError::WriteHeaderError)?;

        Ok(())
    }
```
我对ffmpeg不是很了解，是不是还有其他方法呢？请教一下。

**Comment by ldm0** [comment]
Please check if [this](https://github.com/larksuite/rsmpeg/pull/90/files#diff-c50764ed7004463e8b4656b99e384b6132f90f2e3e26fa85314ccb45c1792aabR553) meets your needs.
